In [1]:
%pylab inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [2]:
def order_book(month,day):
    data = []
    datapath = '/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/High_Frequency_Trading_Strategy_using_machine_learning/Limit_Order_Book_Best_3/order_book_3_2014'\
                + '_' + str(month) + '_' + str(day) + '.csv'
    order_book = pd.read_csv(datapath,sep=',')
    bid_price_1 = np.array(map(float,order_book['Bid'][1::4]))/100.0
    bid_price_2 = np.array(map(float,order_book['Bid'][2::4]))/100.0
    bid_price_3 = np.array(map(float,order_book['Bid'][3::4]))/100.0
    timestamp = np.array(order_book['Bid_Quantity'][0::4])
    bid_quantity_1 = np.array(map(float,order_book['Bid_Quantity'][1::4]))
    bid_quantity_2 = np.array(map(float,order_book['Bid_Quantity'][2::4]))
    bid_quantity_3 = np.array(map(float,order_book['Bid_Quantity'][3::4]))
    ask_price_1 = np.array(map(float,order_book['Ask'][1::4]))/100.0
    ask_price_2 = np.array(map(float,order_book['Ask'][2::4]))/100.0
    ask_price_3 = np.array(map(float,order_book['Ask'][3::4]))/100.0
    ask_quantity_1 = np.array(map(float,order_book['Ask_Quantity'][1::4]))
    ask_quantity_2 = np.array(map(float,order_book['Ask_Quantity'][2::4]))
    ask_quantity_3 = np.array(map(float,order_book['Ask_Quantity'][3::4]))
    
    bid_quantity_1[isnan(bid_quantity_1)] = 0
    bid_quantity_2[isnan(bid_quantity_2)] = 0
    bid_quantity_3[isnan(bid_quantity_3)] = 0
    ask_quantity_1[isnan(ask_quantity_1)] = 0
    ask_quantity_2[isnan(ask_quantity_2)] = 0
    ask_quantity_3[isnan(ask_quantity_3)] = 0
    
    return timestamp,order_book,bid_price_1,bid_price_2,bid_price_3,bid_quantity_1,\
            bid_quantity_2,bid_quantity_3,ask_price_1,ask_price_2,ask_price_3,ask_quantity_1,\
            ask_quantity_2,ask_quantity_3

In [3]:
def time_transform(timestamp_time):
    time_second_basic = []
    time_second = []
    for i in range(0,len(timestamp_time),1):
        second = float(timestamp_time[i][11])*36000 + float(timestamp_time[i][12])*3600+\
                    float(timestamp_time[i][14])*600 + float(timestamp_time[i][15])*60+\
                    float(timestamp_time[i][17])*10 + float(timestamp_time[i][18])  
        time_second_basic.append(second - 32400.0)
        time_second.append(second)
    return np.array(time_second),np.array(time_second_basic)

In [4]:
def weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3):
    
    Weight_Ask = (w1 * ask_quantity_1 + w2 * ask_quantity_2 + w3 * ask_quantity_3)
    Weight_Bid = (w1 * bid_quantity_1 + w2 * bid_quantity_2 + w3 * bid_quantity_3)
    W_AB = Weight_Ask/Weight_Bid
    W_A_B = (Weight_Ask - Weight_Bid)/(Weight_Ask + Weight_Bid)
    
    return W_AB, W_A_B

In [135]:
def Feature_DataFrame_UP(traded_time,time_second_basic,bid_price_1,ask_price_1,rise_ratio_ask_3,\
                      rise_ratio_ask_5,rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11,\
                      rise_ratio_ask_13,W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                      W_AB_910 , W_A_B_910, W_AB_730 , W_A_B_730 ,W_AB_550 , W_A_B_550,\
                      W_AB_721 , W_A_B_721, W_AB_532 , W_A_B_532, W_AB_111 , W_A_B_111):
    # 09:00 ~ 11:30
    time1 = 0
    time2 = 9000
    print len(W_AB_910)
    traded_1 ,index_1,rise_ratio_second_1_3, rise_ratio_second_1_5, rise_ratio_second_1_7,\
    rise_ratio_second_1_9, rise_ratio_second_1_11, rise_ratio_second_1_13, w_divid_1_100, w_diff_1_100,\
    w_divid_1_010, w_diff_1_010,w_divid_1_001, w_diff_1_001,w_divid_1_910, w_diff_1_910,w_divid_1_730,\
    w_diff_1_730,w_divid_1_550, w_diff_1_550,w_divid_1_721, w_diff_1_721,w_divid_1_532, w_diff_1_532,\
    w_divid_1_111, w_diff_1_111 =\
        traded_label_one_second(time1,time2,time_second_basic,bid_price_1,\
                                ask_price_1,traded_time,rise_ratio_ask_3, rise_ratio_ask_5,\
                                rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11, rise_ratio_ask_13,\
                                W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                                W_AB_910, W_A_B_910, W_AB_730, W_A_B_730,W_AB_550, W_A_B_550,\
                                W_AB_721, W_A_B_721, W_AB_532, W_A_B_532, W_AB_111, W_A_B_111)
    
    data = np.array([traded_1,rise_ratio_second_1_3,rise_ratio_second_1_5,rise_ratio_second_1_7,\
                     rise_ratio_second_1_9,rise_ratio_second_1_11,rise_ratio_second_1_13,w_divid_1_100,\
                     w_diff_1_100,w_divid_1_010,w_diff_1_010,w_divid_1_001,w_diff_1_001,w_divid_1_910,\
                     w_diff_1_910,w_divid_1_730,w_diff_1_730,w_divid_1_550,w_diff_1_550,w_divid_1_721,\
                     w_diff_1_721,w_divid_1_532,w_diff_1_532,w_divid_1_111,w_diff_1_111]).T

    return pd.DataFrame(data)#,traded_1 #, columns = ['label', 'rise', 'depth_divid', 'depth_diff'])


def Feature_DataFrame_DOWN(traded_time,time_second_basic,bid_price_1,ask_price_1,rise_ratio_ask_3,\
                          rise_ratio_ask_5,rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11,\
                          rise_ratio_ask_13,W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                          W_AB_910 , W_A_B_910, W_AB_730 , W_A_B_730 ,W_AB_550 , W_A_B_550,\
                          W_AB_721 , W_A_B_721, W_AB_532 , W_A_B_532, W_AB_111 , W_A_B_111):
    # 13:00 ~ 16:00
    time1 = 14400
    time2 = 25200
    traded_2 ,index_2,rise_ratio_second_2_3, rise_ratio_second_2_5, rise_ratio_second_2_7,\
    rise_ratio_second_2_9, rise_ratio_second_2_11, rise_ratio_second_2_13, w_divid_2_100, w_diff_2_100,\
    w_divid_2_010, w_diff_2_010,w_divid_2_001, w_diff_2_001,w_divid_2_910, w_diff_2_910,w_divid_2_730,\
    w_diff_2_730,w_divid_2_550, w_diff_2_550,w_divid_2_721, w_diff_2_721,w_divid_2_532, w_diff_2_532,\
    w_divid_2_111, w_diff_2_111 =\
        traded_label_one_second(time1,time2,time_second_basic,bid_price_1,\
                                ask_price_1,traded_time,rise_ratio_ask_3, rise_ratio_ask_5,\
                                rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11, rise_ratio_ask_13,\
                                W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                                W_AB_910, W_A_B_910, W_AB_730, W_A_B_730 ,W_AB_550, W_A_B_550,\
                                W_AB_721, W_A_B_721, W_AB_532, W_A_B_532, W_AB_111, W_A_B_111)

    data = np.array([traded_2,rise_ratio_second_2_3,rise_ratio_second_2_5,rise_ratio_second_2_7,\
                     rise_ratio_second_2_9,rise_ratio_second_2_11,rise_ratio_second_2_13,w_divid_2_100,\
                     w_diff_2_100,w_divid_2_010,w_diff_2_010,w_divid_2_001,w_diff_2_001,w_divid_2_910,\
                     w_diff_2_910,w_divid_2_730,w_diff_2_730,w_divid_2_550,w_diff_2_550,w_divid_2_721,\
                     w_diff_2_721,w_divid_2_532,w_diff_2_532,w_divid_2_111,w_diff_2_111]).T
        
    return pd.DataFrame(data)#,traded_2 #, columns = ['label', 'rise', 'depth_divid', 'depth_diff'])



In [6]:
def rise_ask(Ask1,timestamp_time_second,before_time):
    Ask1[Ask1 == 0] = mean(Ask1)
    rise_ratio = []
    index = np.where(timestamp_time_second >= before_time)[0][0]
    #open first before_time mins
    for i in range(0,index,1):
        rise_ratio_ = round((Ask1[i] - Ask1[0])*(1.0)/Ask1[0]*100,5)
        rise_ratio.append(rise_ratio_)
    for i in range(index,len(Ask1),1):
        index_start = np.where(timestamp_time_second[:i] >= timestamp_time_second[i] - before_time)[0][0]
        rise_ratio_ = round((Ask1[i] - Ask1[index_start])*(1.0)/Ask1[index_start]*100,5)
        rise_ratio.append(rise_ratio_)
    return np.array(rise_ratio)

In [141]:
def data(month,day,traded_time):
    
    timestamp,order_book_ ,bid_price_1, bid_price_2, bid_price_3,\
    bid_quantity_1, bid_quantity_2, bid_quantity_3,\
    ask_price_1, ask_price_2, ask_price_3,ask_quantity_1,\
    ask_quantity_2, ask_quantity_3 = order_book(month,day)
    
    time_second,time_second_basic = time_transform(timestamp)
    print len(time_second)
    #return bid_quantity_1,ask_quantity_1
    Ask1 = ask_price_1[np.where(time_second_basic <= 0.0)[0][-1]:]
    
    #before_time = 60.0 * 1
    #rise_ratio_ask_1 = rise_ask(Ask1, time_second_basic, before_time)
    before_time = 60.0 * 6
    rise_ratio_ask_3 = rise_ask(Ask1, time_second_basic, before_time)
    #return rise_ratio_ask_3

    before_time = 60.0 * 5
    rise_ratio_ask_5 = rise_ask(Ask1, time_second_basic, before_time)
    before_time = 60.0 * 7
    rise_ratio_ask_7 = rise_ask(Ask1, time_second_basic, before_time)
    before_time = 60.0 * 9
    rise_ratio_ask_9 = rise_ask(Ask1, time_second_basic, before_time)
    before_time = 60.0 * 11
    rise_ratio_ask_11 = rise_ask(Ask1, time_second_basic, before_time)
    before_time = 60.0 * 13
    rise_ratio_ask_13 = rise_ask(Ask1, time_second_basic, before_time)

    #Weight Depth
    w1,w2,w3 = [100.0, 0.0, 0.0]
    W_AB_100 , W_A_B_100 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    #return W_AB_100 , W_A_B_100
    
    w1,w2,w3 = [0.0, 100.0, 0.0]
    W_AB_010 , W_A_B_010 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [0.0, 0.0, 100.0]
    W_AB_001 , W_A_B_001 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [90.0, 10.0, 0.0]
    W_AB_910 , W_A_B_910 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [70.0, 30.0, 0.0]
    W_AB_730 , W_A_B_730 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [50.0, 50.0, 0.0]
    W_AB_550 , W_A_B_550 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [70.0, 20.0, 10.0]
    W_AB_721 , W_A_B_721 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [50.0, 30.0, 20.0]
    W_AB_532 , W_A_B_532 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    w1,w2,w3 = [1.0, 1.0, 1.0]
    W_AB_111 , W_A_B_111 = weight_pecentage(w1,w2,w3,ask_quantity_1,ask_quantity_2,ask_quantity_3,\
                     bid_quantity_1,bid_quantity_2,bid_quantity_3)
    
    data_2014_UP =\
    Feature_DataFrame_UP(traded_time,time_second_basic,bid_price_1,ask_price_1,rise_ratio_ask_3,\
                          rise_ratio_ask_5,rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11,\
                          rise_ratio_ask_13,W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                          W_AB_910 , W_A_B_910, W_AB_730 , W_A_B_730 ,W_AB_550 , W_A_B_550,\
                          W_AB_721 , W_A_B_721, W_AB_532 , W_A_B_532, W_AB_111 , W_A_B_111)
    data_2014_DOWN =\
    Feature_DataFrame_DOWN(traded_time,time_second_basic,bid_price_1,ask_price_1,rise_ratio_ask_3,\
                          rise_ratio_ask_5,rise_ratio_ask_7,rise_ratio_ask_9, rise_ratio_ask_11,\
                          rise_ratio_ask_13,W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                          W_AB_910 , W_A_B_910, W_AB_730 , W_A_B_730 ,W_AB_550 , W_A_B_550,\
                          W_AB_721 , W_A_B_721, W_AB_532 , W_A_B_532, W_AB_111 , W_A_B_111)
    
    return data_2014_UP,data_2014_DOWN,len(W_AB_111)#,trade_1,trade_2#,timestamp

In [79]:
W_AB_100 = data(1,2,600)#/data(1,27,600)[1]

46683


In [22]:
len(time_transform(order_book(1,27)[0])[1])

50063

In [88]:
len(W_AB_100),46683 - index_one

(46389, 46389)

In [89]:
w = []
t = time_transform(order_book(1,2)[0])[1]
index_one = np.where(t <= 0)[0][-1]
for i in range(0,9000,1):
    #print i
    index_array = np.where((t < i+1) & (t >= i))[0]
    print index_array
    if len(index_array) > 0:
        index = index_array[-1]
        #print index + (index - index_one)
        w.append(W_AB_100[(index - index_one)])
    elif len(index_array) == 0:
        w.append(w[-1])

[288 289 290 291 292 293 294]
[]
[295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312
 313 314 315 316 317]
[318 319]
[320 321]
[322 323 324]
[325 326]
[327 328 329 330]
[]
[331 332 333 334]
[335 336 337]
[338 339]
[340 341 342 343 344]
[345 346 347]
[348 349 350 351 352 353]
[]
[]
[354]
[355]
[]
[]
[356 357]
[358]
[359]
[]
[360]
[]
[]
[]
[361 362]
[363 364 365 366 367 368 369]
[370 371 372 373 374]
[375 376 377 378 379]
[380]
[]
[381]
[]
[]
[382 383 384 385]
[386 387 388 389]
[]
[390 391]
[392 393]
[394]
[]
[395 396 397]
[398]
[]
[399]
[400]
[]
[401]
[402]
[403]
[404]
[]
[]
[405]
[406]
[]
[407]
[408]
[]
[409]
[410]
[]
[]
[411]
[412]
[]
[413]
[414]
[415 416]
[417 418]
[419 420 421]
[]
[422]
[423]
[424 425]
[]
[426 427]
[428]
[429 430 431 432 433]
[]
[434]
[435]
[436]
[]
[]
[]
[]
[]
[437]
[]
[]
[438 439 440 441]
[442 443]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[444]
[445]
[446]
[447 448 449 450]
[451 452 453]
[]
[]
[454]
[455]
[456]
[]
[457

In [71]:
len(w)

9000

In [86]:
W_AB_100[index_one:]#[index_one + (258 - index_one)]

array([ 0.28129,  0.28129,  0.28129, ...,  0.     ,  0.     ,  0.     ])

In [163]:
def traded_label_one_second(time1, time2, time_second_basic,\
                            bid_price_1, ask_price_1, traded_time,\
                            rise_ratio_ask_3, rise_ratio_ask_5, rise_ratio_ask_7,\
                            rise_ratio_ask_9, rise_ratio_ask_11, rise_ratio_ask_13,\
                            W_AB_100, W_A_B_100, W_AB_010, W_A_B_010, W_AB_001, W_A_B_001,\
                            W_AB_910 , W_A_B_910, W_AB_730 , W_A_B_730 ,W_AB_550 , W_A_B_550,\
                            W_AB_721 , W_A_B_721, W_AB_532 , W_A_B_532, W_AB_111 , W_A_B_111):
    global index
    traded = []
    index_ = []
    rise_ratio_second_3 = []
    rise_ratio_second_5 = []   
    rise_ratio_second_7 = []
    rise_ratio_second_9 = []
    rise_ratio_second_11 = []
    rise_ratio_second_13 = []
    
    w_divid_100 = []
    w_diff_100 = []
    w_divid_010 = []
    w_diff_010 = []
    w_divid_001 = []
    w_diff_001 = []
    w_divid_910 = []
    w_diff_910 = []
    w_divid_730 = []
    w_diff_730 = []
    w_divid_550 = []
    w_diff_550 = []
    w_divid_721 = []
    w_diff_721 = []
    w_divid_532 = []
    w_diff_532 = []
    w_divid_111 = []
    w_diff_111 = []
    
    index_one = np.where(time_second_basic <= 0)[0][-1]
    for i in range(time1, time2, 1):
        #print i
        index_array = np.where((time_second_basic < i+1) & (time_second_basic >= i))[0]      
        print index_array,len(index_array)
        if len(index_array) > 0:
            index = index_array[-1]
            if i == time1:
                index_.append(index)
            if i == time2 - 1:
                index_.append(index)
            if i < 25200 - traded_time:
                #print i
                index_min = np.where(time_second_basic <= i + traded_time)[0][-1]
                #print index,index_min
                #print time_second_basic[index],time_second_basic[index_min]
                traded_min = ask_price_1[index:index_min]

                #if len(traded_min) > 0:
                if bid_price_1[index] > min(traded_min):
                    traded.append(1)
                else:
                    traded.append(0)

            elif i >= 25200 - traded_time:
                if bid_price_1[index] > ask_price_1[-1]:
                    traded.append(1)
                else:
                    traded.append(0)
                    
            rise_ratio_second_3.append(rise_ratio_ask_3[(index - index_one)])
            rise_ratio_second_5.append(rise_ratio_ask_5[(index - index_one)])
            rise_ratio_second_7.append(rise_ratio_ask_7[(index - index_one)])
            rise_ratio_second_9.append(rise_ratio_ask_9[(index - index_one)])
            rise_ratio_second_11.append(rise_ratio_ask_11[(index - index_one)])
            rise_ratio_second_13.append(rise_ratio_ask_13[(index - index_one)])

            w_divid_100.append(W_AB_100[index_one + (index - index_one)])
            w_diff_100.append(W_A_B_100[index_one + (index - index_one)])
            w_divid_010.append(W_AB_010[index_one + (index - index_one)])
            w_diff_010.append(W_A_B_010[index_one + (index - index_one)])
            w_divid_001.append(W_AB_001[index_one + (index - index_one)])
            w_diff_001.append(W_A_B_001[index_one + (index - index_one)])
            w_divid_910.append(W_AB_910[index_one + (index - index_one)])
            w_diff_910.append(W_A_B_910[index_one + (index - index_one)])
            w_divid_730.append(W_AB_730[index_one + (index - index_one)])
            w_diff_730.append(W_A_B_730[index_one + (index - index_one)])
            w_divid_550.append(W_AB_550[index_one + (index - index_one)])
            w_diff_550.append(W_A_B_550[index_one + (index - index_one)])
            w_divid_721.append(W_AB_721[index_one + (index - index_one)])
            w_diff_721.append(W_A_B_721[index_one + (index - index_one)])
            w_divid_532.append(W_AB_532[index_one + (index - index_one)])
            w_diff_532.append(W_A_B_532[index_one + (index - index_one)])
            w_divid_111.append(W_AB_111[index_one + (index - index_one)])
            w_diff_111.append(W_A_B_111[index_one + (index - index_one)])
        
        elif len(index_array) == 0:
            
            if i < 25200 - traded_time:
                index_min = np.where(time_second_basic <= i + traded_time)[0][-1]
                traded_min = ask_price_1[index:index_min]
                if bid_price_1[index] > min(traded_min):
                    traded.append(1)
                else:
                    traded.append(0)

            elif i >= 25200 - traded_time:
                if bid_price_1[index] > ask_price_1[-1]:
                    traded.append(1)
                else:
                    traded.append(0)
            print  rise_ratio_second_3
            rise_ratio_second_3.append(rise_ratio_second_3[-1])
            rise_ratio_second_5.append(rise_ratio_second_5[-1])
            rise_ratio_second_7.append(rise_ratio_second_7[-1])
            rise_ratio_second_9.append(rise_ratio_second_9[-1])
            rise_ratio_second_11.append(rise_ratio_second_11[-1])
            rise_ratio_second_13.append(rise_ratio_second_13[-1])

            w_divid_100.append(w_divid_100[-1])
            w_diff_100.append(w_diff_100[-1])
            w_divid_010.append(w_divid_010[-1])
            w_diff_010.append(w_diff_010[-1])
            w_divid_001.append(w_divid_001[-1])
            w_diff_001.append(w_diff_001[-1])
            w_divid_910.append(w_divid_910[-1])
            w_diff_910.append(w_diff_910[-1])
            w_divid_730.append(w_divid_730[-1])
            w_diff_730.append(w_diff_730[-1])
            w_divid_550.append(w_divid_550[-1])
            w_diff_550.append(w_diff_550[-1])
            w_divid_721.append(w_divid_721[-1])
            w_diff_721.append(w_diff_721[-1])
            w_divid_532.append(w_divid_532[-1])
            w_diff_532.append(w_diff_532[-1])
            w_divid_111.append(w_divid_111[-1])
            w_diff_111.append(w_diff_111[-1])
            
    return traded, index_, rise_ratio_second_3, rise_ratio_second_5, rise_ratio_second_7,\
            rise_ratio_second_9, rise_ratio_second_11, rise_ratio_second_13, w_divid_100, w_diff_100,\
            w_divid_010, w_diff_010,w_divid_001, w_diff_001,w_divid_910, w_diff_910,w_divid_730, w_diff_730,\
            w_divid_550, w_diff_550,w_divid_721, w_diff_721,w_divid_532, w_diff_532,w_divid_111, w_diff_111

In [166]:
data_1_14_UP,data_1_14_DOWN,len_ = data(1,14,600)

65478


KeyboardInterrupt: 

In [156]:
import time 
start = time.time()

traded_time = 600
#data_1_2_UP,data_1_2_DOWN,len_ = data(1,2,traded_time)
#data_1_3_UP,data_1_3_DOWN,len_ = data(1,3,traded_time)
#data_1_6_UP,data_1_6_DOWN,len_ = data(1,6,traded_time)
#data_1_7_UP,data_1_7_DOWN,len_ = data(1,7,traded_time)
#data_1_8_UP,data_1_8_DOWN,len_ = data(1,8,traded_time)
#data_1_10_UP,data_1_10_DOWN,len_ = data(1,10,traded_time)
#data_1_13_UP,data_1_13_DOWN,len_ = data(1,13,traded_time)
data_1_14_UP,data_1_14_DOWN,len_ = data(1,14,traded_time)
#data_1_15_UP,data_1_15_DOWN,len_ = data(1,15,traded_time)
#data_1_16_UP,data_1_16_DOWN,len_ = data(1,16,traded_time)
#data_1_17_UP,data_1_17_DOWN,len_ = data(1,17,traded_time)
#data_1_20_UP,data_1_20_DOWN,len_ = data(1,20,traded_time)
#data_1_21_UP,data_1_21_DOWN,len_ = data(1,21,traded_time)
#data_1_22_UP,data_1_22_DOWN,len_ = data(1,22,traded_time)
#data_1_23_UP,data_1_23_DOWN,len_ = data(1,23,traded_time)
#data_1_24_UP,data_1_24_DOWN,len_ = data(1,24,traded_time)
#data_1_27_UP,data_1_27_DOWN,len_ = data(1,27,traded_time)
#data_1_28_UP,data_1_28_DOWN,len_ = data(1,28,traded_time)
#data_1_29_UP,data_1_29_DOWN,len_ = data(1,29,traded_time)
#data_1_30_UP,data_1_30_DOWN,len_ = data(1,30,traded_time)

end = time.time()  
print "Total time = %f"%(end - start)

65478
65478


IndexError: list index out of range

In [94]:
data_1_2.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_1.csv', index = False)

In [95]:
data_1_3.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_2.csv', index = False)

In [96]:
data_1_6.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_3.csv', index = False)

In [97]:
data_1_7.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_4.csv', index = False)

In [98]:
data_1_8.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_5.csv', index = False)

In [100]:
data_1_10.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_6.csv', index = False)

In [101]:
data_1_13.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_7.csv', index = False)

In [102]:
data_1_14.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_8.csv', index = False)

In [103]:
data_1_15.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_9.csv', index = False)

In [104]:
data_1_16.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_10.csv', index = False)

In [105]:
data_1_17.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_11.csv', index = False)

In [106]:
data_1_20.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_12.csv', index = False)

In [107]:
data_1_21.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_13.csv', index = False)

In [108]:
data_1_22.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_14.csv', index = False)

In [109]:
data_1_23.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_15.csv', index = False)

In [110]:
data_1_24.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_16.csv', index = False)

In [111]:
data_1_27.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_17.csv', index = False)

In [112]:
data_1_28.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_18.csv', index = False)

In [113]:
data_1_29.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_19.csv', index = False)

In [114]:
data_1_30.to_csv('/home/bigdatas16/SGX-OrderBook-Tick-Data-Trading-Strategy-/Train_Test_Data/ML_data_2014_1_20.csv', index = False)